In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

## Data preprocess

In [2]:
df = pd.read_csv('Miner_ROI_analyse.csv')
df

发货期          型号  T数   矿机价格        单T价格       购机当日币价￥       当日可买BTC  \
0    2019-8-15  S17 PRO-50  50  26500  530.000000  70593.670890      0.375388   
1    2019-8-15  S17 PRO-50  50  26500  530.000000  70593.670890      0.375388   
2    2019-8-15  S17 PRO-50  50  27800  556.000000  70593.670890      0.393803   
3    2019-8-15  S17 PRO-50  50  27800  556.000000  70593.670890      0.393803   
4    2019-8-15  S17 PRO-50  50  27800  556.000000  70593.670890      0.393803   
5    2019-8-15  S17 PRO-50  50  27800  556.000000  70593.670890      0.393803   
6    2019-8-15  S17 PRO-50  50  26800  536.000000  70593.670890      0.379637   
7    2019-8-20  S17 PRO-50  50  26500  530.000000  76984.132580      0.344227   
8    2019-8-25  S17 PRO-50  50  27200  544.000000  72113.129880      0.377185   
9    2019-8-25  S17 PRO-50  50  26500  530.000000  72113.129880      0.367478   
10    2019-9-6  S17 PRO-50  50  26200  524.000000  75612.580410      0.346503   
11    2019-9-6  S17 PRO-50  50  23800  476.000000  75612.580410      0.314762   
12   2019-9-10  S17 PRO-50  50  25500  510.000000  73621.153850      0.346368   
13   2019-9-20  S17 PRO-50  50  25000  500.000000  72862.455640      0.343112   
14  2019-10-30  S17 PRO-50  50  16800  336.000000  66542.796610      0.252469   
15   2019-11-4  S17 PRO-50  50  16800  336.000000  64993.736810      0.258486   
16   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
17   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
18   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
19   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
20   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
21   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
22   2019-9-25     M20S-68  68  20500  301.470588  61234.377220      0.334779   
23   2019-9-25     M20S-68  68  19500  286.764706  61234.377220      0.318449   
24   2019-9-25     M20S-68  68  20000  294.117647  61234.377220      0.326614   
25   2019-8-26     M20S-68  68  24800  364.705882  72279.086370      0.343114   
26    2019-9-5     M20S-68  68  21600  317.647059  75738.054360      0.285193   
27   2019-9-25     M20S-68  68  21000  308.823529  61234.377220      0.342945   
28  2019-10-11     M20S-68  68  18500  272.058823  61105.053380      0.302757   
29  2019-10-25     M20S-68  68  17500  257.352941  53012.738850      0.330109   
30  2019-10-25     M20S-68  68  17300  254.411765  53012.738850      0.326337   
31  2019-10-30     M20S-68  68  16650  244.852941  66542.796610      0.250215   
32  2019-10-25     M20S-68  68  16800  247.058823  53012.738850      0.316905   
33   2019-11-4     M20S-68  68  16650  244.852941  64993.736810      0.256179   
34   2019-11-4     M20S-68  68  16700  245.588235  64993.736810      0.256948   
35    2019-8-5      S9K-14  14   3350  239.285714  76917.473680      0.043553   
36    2019-8-6      S9K-14  14   3250  232.142857  83238.548270      0.039044   
37    2019-8-7      S9K-14  14   3250  232.142857  80761.365240      0.040242   
38    2019-8-8      S9K-14  14   3250  232.142857  84421.186440      0.038497   
39    2019-8-9      S9K-14  14   3250  232.142857  84238.689220      0.038581   
40   2019-8-10      S9K-14  14   3250  232.142857  83590.979560      0.038880   
41   2019-8-15      S9K-14  14   2600  185.714286  70593.670890      0.036830   
42   2019-8-26      S9K-14  14   2300  164.285714  72279.086370      0.031821   
43   2019-9-19      S9K-14  14   1980  141.428571  72292.700210      0.027389   
44   2019-9-23      S9K-14  14   1950  139.285714  71353.366410      0.027329   
45   2019-9-29      S9K-14  14   1750  125.000000  58816.262480      0.029754   
46  2019-10-11      S9K-14  14   1480  105.714286      0.145163  10195.412970   

     累计挖矿BTC      累计挖矿RMB   ROI BTC     ROI ￥    每T理论产出（难度）     历史7日币价平均  \
0   0.088502  5872.891970  0.235761  0.221619 

In [3]:
data = df.copy()
data.head()

发货期          型号  T数   矿机价格   单T价格      购机当日币价￥   当日可买BTC   累计挖矿BTC  \
0  2019-8-15  S17 PRO-50  50  26500  530.0  70593.67089  0.375388  0.088502   
1  2019-8-15  S17 PRO-50  50  26500  530.0  70593.67089  0.375388  0.088502   
2  2019-8-15  S17 PRO-50  50  27800  556.0  70593.67089  0.393803  0.088502   
3  2019-8-15  S17 PRO-50  50  27800  556.0  70593.67089  0.393803  0.088502   
4  2019-8-15  S17 PRO-50  50  27800  556.0  70593.67089  0.393803  0.088502   

      累计挖矿RMB   ROI BTC     ROI ￥  每T理论产出（难度）    历史7日币价平均    历史10日币价平均  \
0  5872.89197  0.235761  0.221619    0.000025  79528.0017  80511.71118   
1  5872.89197  0.235761  0.221619    0.000025  79528.0017  80511.71118   
2  5872.89197  0.224737  0.211255    0.000025  79528.0017  80511.71118   
3  5872.89197  0.224737  0.211255    0.000025  79528.0017  80511.71118   
4  5872.89197  0.224737  0.211255    0.000025  79528.0017  80511.71118   

    历史14日币价平均    历史30日币价平均    历史60日币价平均  历史30日币价波动率  历史60日币价波动率  
0  78650.1831  73343.31956  74605.94049      0.8527    1.031485  
1  78650.1831  73343.31956  74605.94049      0.8527    1.031485  
2  78650.1831  73343.31956  74605.94049      0.8527    1.031485  
3  78650.1831  73343.31956  74605.94049      0.8527    1.031485  
4  78650.1831  73343.31956  74605.94049      0.8527    1.031485

**Check point**

In [4]:
raw_csv_data = data.drop(['T数','当日可买BTC'],axis=1)
raw_csv_data

发货期          型号   矿机价格        单T价格       购机当日币价￥   累计挖矿BTC  \
0    2019-8-15  S17 PRO-50  26500  530.000000  70593.670890  0.088502   
1    2019-8-15  S17 PRO-50  26500  530.000000  70593.670890  0.088502   
2    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
3    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
4    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
5    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
6    2019-8-15  S17 PRO-50  26800  536.000000  70593.670890  0.088502   
7    2019-8-20  S17 PRO-50  26500  530.000000  76984.132580  0.086105   
8    2019-8-25  S17 PRO-50  27200  544.000000  72113.129880  0.083874   
9    2019-8-25  S17 PRO-50  26500  530.000000  72113.129880  0.083874   
10    2019-9-6  S17 PRO-50  26200  524.000000  75612.580410  0.078784   
11    2019-9-6  S17 PRO-50  23800  476.000000  75612.580410  0.078784   
12   2019-9-10  S17 PRO-50  25500  510.000000  73621.153850  0.077185   
13   2019-9-20  S17 PRO-50  25000  500.000000  72862.455640  0.073816   
14  2019-10-30  S17 PRO-50  16800  336.000000  66542.796610  0.066975   
15   2019-11-4  S17 PRO-50  16800  336.000000  64993.736810  0.066686   
16   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
17   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
18   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
19   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
20   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
21   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
22   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
23   2019-9-25     M20S-68  19500  286.764706  61234.377220  0.091035   
24   2019-9-25     M20S-68  20000  294.117647  61234.377220  0.091035   
25   2019-8-26     M20S-68  24800  364.705882  72279.086370  0.107612   
26    2019-9-5     M20S-68  21600  317.647059  75738.054360  0.101311   
27   2019-9-25     M20S-68  21000  308.823529  61234.377220  0.091035   
28  2019-10-11     M20S-68  18500  272.058823  61105.053380  0.085495   
29  2019-10-25     M20S-68  17500  257.352941  53012.738850  0.080936   
30  2019-10-25     M20S-68  17300  254.411765  53012.738850  0.080936   
31  2019-10-30     M20S-68  16650  244.852941  66542.796610  0.079522   
32  2019-10-25     M20S-68  16800  247.058823  53012.738850  0.080936   
33   2019-11-4     M20S-68  16650  244.852941  64993.736810  0.078148   
34   2019-11-4     M20S-68  16700  245.588235  64993.736810  0.078148   
35    2019-8-5      S9K-14   3350  239.285714  76917.473680  0.020275   
36    2019-8-6      S9K-14   3250  232.142857  83238.548270  0.020142   
37    2019-8-7      S9K-14   3250  232.142857  80761.365240  0.020007   
38    2019-8-8      S9K-14   3250  232.142857  84421.186440  0.019901   
39    2019-8-9      S9K-14   3250  232.142857  84238.689220  0.019796   
40   2019-8-10      S9K-14   3250  232.142857  83590.979560  0.019687   
41   2019-8-15      S9K-14   2600  185.714286  70593.670890  0.018991   
42   2019-8-26      S9K-14   2300  164.285714  72279.086370  0.016919   
43   2019-9-19      S9K-14   1980  141.428571  72292.700210  0.012853   
44   2019-9-23      S9K-14   1950  139.285714  71353.366410  0.012310   
45   2019-9-29      S9K-14   1750  125.000000  58816.262480  0.011479   
46  2019-10-11      S9K-14   1480  105.714286      0.145163  0.010369   

        累计挖矿RMB   ROI BTC     ROI ￥    每T理论产出（难度）     历史7日币价平均    历史10日币价平均  \
0   5872.891970  0.235761  0.221619      0.000025  79528.00170  80511.71118   
1   5872.891970  0.235761  0.221619      0.000025  79528.00170  80511.71118   
2   5872.891970  0.224737  0.211255      0.000025  79528.00170  80511.71118   
3   5872.891970  0.224737  0.211255      0.000025  79528.00170  80511.71118   
4   5872.891970  0.224737  0.211255      0.000025  79528.00170  80511.71118   
5   5872.891970  0.224737  0.211

In [5]:
raw_csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 17 columns):
发货期           47 non-null object
型号            47 non-null object
矿机价格          47 non-null int64
单T价格          47 non-null float64
购机当日币价￥       47 non-null float64
累计挖矿BTC       47 non-null float64
累计挖矿RMB       47 non-null float64
ROI BTC       47 non-null float64
ROI ￥         47 non-null float64
每T理论产出（难度）    47 non-null float64
历史7日币价平均      47 non-null float64
历史10日币价平均     47 non-null float64
历史14日币价平均     47 non-null float64
历史30日币价平均     47 non-null float64
历史60日币价平均     47 non-null float64
历史30日币价波动率    47 non-null float64
历史60日币价波动率    47 non-null float64
dtypes: float64(14), int64(1), object(2)
memory usage: 6.3+ KB


**ROI BTC**

In [6]:
raw_csv_data['ROI BTC'].min()

0.215136418

In [7]:
raw_csv_data['ROI BTC'].max()

0.531693005

In [8]:
raw_csv_data['ROI ￥'].max()

0.48840528899999996

In [9]:
raw_csv_data['ROI ￥'].unique()

array([0.22161856, 0.21125511, 0.21913776, 0.21241469, 0.19844654,
       0.20368852, 0.18627634, 0.20506051, 0.18412338, 0.17239977,
       0.22781751, 0.22747676, 0.25481771, 0.26788528, 0.26118815,
       0.27890361, 0.29267561, 0.24875062, 0.26213547, 0.26337583,
       0.26642064, 0.27273151, 0.27434983, 0.26812902, 0.26732624,
       0.41940998, 0.4285981 , 0.42462383, 0.42080164, 0.41711983,
       0.41307591, 0.48840529, 0.47899447, 0.38992913, 0.37285349,
       0.3817421 , 0.39865745])

In [10]:
sorted(raw_csv_data['ROI ￥'].unique())

[0.172399768,
 0.184123378,
 0.18627634399999998,
 0.19844653899999998,
 0.203688523,
 0.205060513,
 0.211255107,
 0.21241469300000002,
 0.21913776,
 0.221618565,
 0.227476763,
 0.22781751100000003,
 0.24875061699999998,
 0.254817705,
 0.261188147,
 0.262135469,
 0.263375834,
 0.266420641,
 0.26732624,
 0.267885279,
 0.268129021,
 0.272731514,
 0.274349827,
 0.278903613,
 0.292675605,
 0.37285349,
 0.381742095,
 0.389929133,
 0.39865744799999997,
 0.41307591200000005,
 0.41711982700000005,
 0.419409979,
 0.420801637,
 0.424623834,
 0.428598104,
 0.47899446700000003,
 0.48840528899999996]

In [11]:
raw_csv_data.columns.values

array(['发货期', '型号', '矿机价格', '单T价格', '购机当日币价￥', '累计挖矿BTC', '累计挖矿RMB',
       'ROI BTC', 'ROI ￥', '每T理论产出（难度）', '历史7日币价平均', '历史10日币价平均',
       '历史14日币价平均', '历史30日币价平均', '历史60日币价平均', '历史30日币价波动率', '历史60日币价波动率'],
      dtype=object)

In [12]:
column_names_reordered = ['发货期', '型号', '矿机价格', '单T价格', '购机当日币价￥', '累计挖矿BTC', '累计挖矿RMB',
       '每T理论产出（难度）', '历史7日币价平均', '历史10日币价平均',
       '历史14日币价平均', '历史30日币价平均','历史60日币价平均', '历史30日币价波动率', '历史60日币价波动率','ROI BTC', 'ROI ￥']

In [13]:
df = raw_csv_data[column_names_reordered]
df.head()

发货期          型号   矿机价格   单T价格      购机当日币价￥   累计挖矿BTC     累计挖矿RMB  \
0  2019-8-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
1  2019-8-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
2  2019-8-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
3  2019-8-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
4  2019-8-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   

   每T理论产出（难度）    历史7日币价平均    历史10日币价平均   历史14日币价平均    历史30日币价平均    历史60日币价平均  \
0    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
1    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
2    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
3    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
4    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   

   历史30日币价波动率  历史60日币价波动率   ROI BTC     ROI ￥  
0      0.8527    1.031485  0.235761  0.221619  
1      0.8527    1.031485  0.235761  0.221619  
2      0.8527    1.031485  0.224737  0.211255  
3      0.8527    1.031485  0.224737  0.211255  
4      0.8527    1.031485  0.224737  0.211255

**Get dummies**

In [14]:
machine_models = pd.get_dummies(raw_csv_data['型号'])
machine_models.head()

M20S-68  S17 PRO-50  S9K-14
0        0           1       0
1        0           1       0
2        0           1       0
3        0           1       0
4        0           1       0

In [15]:
machine_models['check'] = machine_models.sum(axis=1)
machine_models.tail()

M20S-68  S17 PRO-50  S9K-14  check
42        0           0       1      1
43        0           0       1      1
44        0           0       1      1
45        0           0       1      1
46        0           0       1      1

In [16]:
machine_models['check'].sum(axis=0)

47

In [17]:
machine_models['check'].unique()

array([1], dtype=int64)

In [18]:
machine_models = machine_models.drop(['check'],axis=1)
machine_models.head()

M20S-68  S17 PRO-50  S9K-14
0        0           1       0
1        0           1       0
2        0           1       0
3        0           1       0
4        0           1       0

**Concatenate columns values**

In [19]:
df

发货期          型号   矿机价格        单T价格       购机当日币价￥   累计挖矿BTC  \
0    2019-8-15  S17 PRO-50  26500  530.000000  70593.670890  0.088502   
1    2019-8-15  S17 PRO-50  26500  530.000000  70593.670890  0.088502   
2    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
3    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
4    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
5    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
6    2019-8-15  S17 PRO-50  26800  536.000000  70593.670890  0.088502   
7    2019-8-20  S17 PRO-50  26500  530.000000  76984.132580  0.086105   
8    2019-8-25  S17 PRO-50  27200  544.000000  72113.129880  0.083874   
9    2019-8-25  S17 PRO-50  26500  530.000000  72113.129880  0.083874   
10    2019-9-6  S17 PRO-50  26200  524.000000  75612.580410  0.078784   
11    2019-9-6  S17 PRO-50  23800  476.000000  75612.580410  0.078784   
12   2019-9-10  S17 PRO-50  25500  510.000000  73621.153850  0.077185   
13   2019-9-20  S17 PRO-50  25000  500.000000  72862.455640  0.073816   
14  2019-10-30  S17 PRO-50  16800  336.000000  66542.796610  0.066975   
15   2019-11-4  S17 PRO-50  16800  336.000000  64993.736810  0.066686   
16   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
17   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
18   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
19   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
20   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
21   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
22   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
23   2019-9-25     M20S-68  19500  286.764706  61234.377220  0.091035   
24   2019-9-25     M20S-68  20000  294.117647  61234.377220  0.091035   
25   2019-8-26     M20S-68  24800  364.705882  72279.086370  0.107612   
26    2019-9-5     M20S-68  21600  317.647059  75738.054360  0.101311   
27   2019-9-25     M20S-68  21000  308.823529  61234.377220  0.091035   
28  2019-10-11     M20S-68  18500  272.058823  61105.053380  0.085495   
29  2019-10-25     M20S-68  17500  257.352941  53012.738850  0.080936   
30  2019-10-25     M20S-68  17300  254.411765  53012.738850  0.080936   
31  2019-10-30     M20S-68  16650  244.852941  66542.796610  0.079522   
32  2019-10-25     M20S-68  16800  247.058823  53012.738850  0.080936   
33   2019-11-4     M20S-68  16650  244.852941  64993.736810  0.078148   
34   2019-11-4     M20S-68  16700  245.588235  64993.736810  0.078148   
35    2019-8-5      S9K-14   3350  239.285714  76917.473680  0.020275   
36    2019-8-6      S9K-14   3250  232.142857  83238.548270  0.020142   
37    2019-8-7      S9K-14   3250  232.142857  80761.365240  0.020007   
38    2019-8-8      S9K-14   3250  232.142857  84421.186440  0.019901   
39    2019-8-9      S9K-14   3250  232.142857  84238.689220  0.019796   
40   2019-8-10      S9K-14   3250  232.142857  83590.979560  0.019687   
41   2019-8-15      S9K-14   2600  185.714286  70593.670890  0.018991   
42   2019-8-26      S9K-14   2300  164.285714  72279.086370  0.016919   
43   2019-9-19      S9K-14   1980  141.428571  72292.700210  0.012853   
44   2019-9-23      S9K-14   1950  139.285714  71353.366410  0.012310   
45   2019-9-29      S9K-14   1750  125.000000  58816.262480  0.011479   
46  2019-10-11      S9K-14   1480  105.714286      0.145163  0.010369   

        累计挖矿RMB    每T理论产出（难度）     历史7日币价平均    历史10日币价平均    历史14日币价平均  \
0   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
1   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
2   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
3   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
4   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
5   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
6 

In [20]:
df = pd.concat([df,machine_models],axis=1)
df.head()

发货期          型号   矿机价格   单T价格      购机当日币价￥   累计挖矿BTC     累计挖矿RMB  \
0  2019-8-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
1  2019-8-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
2  2019-8-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
3  2019-8-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
4  2019-8-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   

   每T理论产出（难度）    历史7日币价平均    历史10日币价平均   历史14日币价平均    历史30日币价平均    历史60日币价平均  \
0    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
1    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
2    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
3    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   
4    0.000025  79528.0017  80511.71118  78650.1831  73343.31956  74605.94049   

   历史30日币价波动率  历史60日币价波动率   ROI BTC     ROI ￥  M20S-68  S17 PRO-50  S9K-14  
0      0.8527    1.031485  0.235761  0.221619        0           1       0  
1      0.8527    1.031485  0.235761  0.221619        0           1       0  
2      0.8527    1.031485  0.224737  0.211255        0           1       0  
3      0.8527    1.031485  0.224737  0.211255        0           1       0  
4      0.8527    1.031485  0.224737  0.211255        0           1       0

**Create another Checkpoint**

In [21]:
df_mod = df.copy()
df_mod

发货期          型号   矿机价格        单T价格       购机当日币价￥   累计挖矿BTC  \
0    2019-8-15  S17 PRO-50  26500  530.000000  70593.670890  0.088502   
1    2019-8-15  S17 PRO-50  26500  530.000000  70593.670890  0.088502   
2    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
3    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
4    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
5    2019-8-15  S17 PRO-50  27800  556.000000  70593.670890  0.088502   
6    2019-8-15  S17 PRO-50  26800  536.000000  70593.670890  0.088502   
7    2019-8-20  S17 PRO-50  26500  530.000000  76984.132580  0.086105   
8    2019-8-25  S17 PRO-50  27200  544.000000  72113.129880  0.083874   
9    2019-8-25  S17 PRO-50  26500  530.000000  72113.129880  0.083874   
10    2019-9-6  S17 PRO-50  26200  524.000000  75612.580410  0.078784   
11    2019-9-6  S17 PRO-50  23800  476.000000  75612.580410  0.078784   
12   2019-9-10  S17 PRO-50  25500  510.000000  73621.153850  0.077185   
13   2019-9-20  S17 PRO-50  25000  500.000000  72862.455640  0.073816   
14  2019-10-30  S17 PRO-50  16800  336.000000  66542.796610  0.066975   
15   2019-11-4  S17 PRO-50  16800  336.000000  64993.736810  0.066686   
16   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
17   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
18   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
19   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
20   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
21   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
22   2019-9-25     M20S-68  20500  301.470588  61234.377220  0.091035   
23   2019-9-25     M20S-68  19500  286.764706  61234.377220  0.091035   
24   2019-9-25     M20S-68  20000  294.117647  61234.377220  0.091035   
25   2019-8-26     M20S-68  24800  364.705882  72279.086370  0.107612   
26    2019-9-5     M20S-68  21600  317.647059  75738.054360  0.101311   
27   2019-9-25     M20S-68  21000  308.823529  61234.377220  0.091035   
28  2019-10-11     M20S-68  18500  272.058823  61105.053380  0.085495   
29  2019-10-25     M20S-68  17500  257.352941  53012.738850  0.080936   
30  2019-10-25     M20S-68  17300  254.411765  53012.738850  0.080936   
31  2019-10-30     M20S-68  16650  244.852941  66542.796610  0.079522   
32  2019-10-25     M20S-68  16800  247.058823  53012.738850  0.080936   
33   2019-11-4     M20S-68  16650  244.852941  64993.736810  0.078148   
34   2019-11-4     M20S-68  16700  245.588235  64993.736810  0.078148   
35    2019-8-5      S9K-14   3350  239.285714  76917.473680  0.020275   
36    2019-8-6      S9K-14   3250  232.142857  83238.548270  0.020142   
37    2019-8-7      S9K-14   3250  232.142857  80761.365240  0.020007   
38    2019-8-8      S9K-14   3250  232.142857  84421.186440  0.019901   
39    2019-8-9      S9K-14   3250  232.142857  84238.689220  0.019796   
40   2019-8-10      S9K-14   3250  232.142857  83590.979560  0.019687   
41   2019-8-15      S9K-14   2600  185.714286  70593.670890  0.018991   
42   2019-8-26      S9K-14   2300  164.285714  72279.086370  0.016919   
43   2019-9-19      S9K-14   1980  141.428571  72292.700210  0.012853   
44   2019-9-23      S9K-14   1950  139.285714  71353.366410  0.012310   
45   2019-9-29      S9K-14   1750  125.000000  58816.262480  0.011479   
46  2019-10-11      S9K-14   1480  105.714286      0.145163  0.010369   

        累计挖矿RMB    每T理论产出（难度）     历史7日币价平均    历史10日币价平均    历史14日币价平均  \
0   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
1   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
2   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
3   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
4   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
5   5872.891970      0.000025  79528.00170  80511.71118  78650.18310   
6 

In [22]:
type(df_mod['发货期'][0])

str

In [23]:
df_mod['发货期']=pd.to_datetime(df_mod['发货期'])
df_mod['发货期']

0    2019-08-15
1    2019-08-15
2    2019-08-15
3    2019-08-15
4    2019-08-15
5    2019-08-15
6    2019-08-15
7    2019-08-20
8    2019-08-25
9    2019-08-25
10   2019-09-06
11   2019-09-06
12   2019-09-10
13   2019-09-20
14   2019-10-30
15   2019-11-04
16   2019-09-25
17   2019-09-25
18   2019-09-25
19   2019-09-25
20   2019-09-25
21   2019-09-25
22   2019-09-25
23   2019-09-25
24   2019-09-25
25   2019-08-26
26   2019-09-05
27   2019-09-25
28   2019-10-11
29   2019-10-25
30   2019-10-25
31   2019-10-30
32   2019-10-25
33   2019-11-04
34   2019-11-04
35   2019-08-05
36   2019-08-06
37   2019-08-07
38   2019-08-08
39   2019-08-09
40   2019-08-10
41   2019-08-15
42   2019-08-26
43   2019-09-19
44   2019-09-23
45   2019-09-29
46   2019-10-11
Name: 发货期, dtype: datetime64[ns]

In [24]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 20 columns):
发货期           47 non-null datetime64[ns]
型号            47 non-null object
矿机价格          47 non-null int64
单T价格          47 non-null float64
购机当日币价￥       47 non-null float64
累计挖矿BTC       47 non-null float64
累计挖矿RMB       47 non-null float64
每T理论产出（难度）    47 non-null float64
历史7日币价平均      47 non-null float64
历史10日币价平均     47 non-null float64
历史14日币价平均     47 non-null float64
历史30日币价平均     47 non-null float64
历史60日币价平均     47 non-null float64
历史30日币价波动率    47 non-null float64
历史60日币价波动率    47 non-null float64
ROI BTC       47 non-null float64
ROI ￥         47 non-null float64
M20S-68       47 non-null uint8
S17 PRO-50    47 non-null uint8
S9K-14        47 non-null uint8
dtypes: datetime64[ns](1), float64(14), int64(1), object(1), uint8(3)
memory usage: 6.5+ KB


**Extract the Month Value:**

In [25]:
df_mod['发货期'][0]

Timestamp('2019-08-15 00:00:00')

In [26]:
df_mod['发货期'][0].month

8

In [27]:
list_month = []
list_month

[]

In [28]:
df_mod.shape

(47, 20)

In [29]:
for i in range(df_mod.shape[0]):
    list_month.append(df_mod['发货期'][i].month)

In [30]:
list_month

[8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 10,
 11,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 10]

In [31]:
len(list_month)

47

In [32]:
df_mod['Month Value'] = list_month
df_mod.head(10)

发货期          型号   矿机价格   单T价格      购机当日币价￥   累计挖矿BTC      累计挖矿RMB  \
0 2019-08-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.891970   
1 2019-08-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.891970   
2 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.891970   
3 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.891970   
4 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.891970   
5 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.891970   
6 2019-08-15  S17 PRO-50  26800  536.0  70593.67089  0.088502  5872.891970   
7 2019-08-20  S17 PRO-50  26500  530.0  76984.13258  0.086105  5628.989376   
8 2019-08-25  S17 PRO-50  27200  544.0  72113.12988  0.083874  5397.745863   
9 2019-08-25  S17 PRO-50  26500  530.0  72113.12988  0.083874  5397.745863   

   每T理论产出（难度）     历史7日币价平均    历史10日币价平均  ...    历史30日币价平均    历史60日币价平均  \
0    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
1    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
2    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
3    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
4    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
5    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
6    0.000025  79528.00170  80511.71118  ...  73343.31956  74605.94049   
7    0.000025  73495.60014  75627.07355  ...  73869.12852  75416.87480   
8    0.000025  73641.61434  73302.22645  ...  74466.63408  75271.76292   
9    0.000025  73641.61434  73302.22645  ...  74466.63408  75271.76292   

   历史30日币价波动率  历史60日币价波动率   ROI BTC     ROI ￥  M20S-68  S17 PRO-50  S9K-14  \
0    0.852700    1.031485  0.235761  0.221619        0           1       0   
1    0.852700    1.031485  0.235761  0.221619        0           1       0   
2    0.852700    1.031485  0.224737  0.211255        0           1       0   
3    0.852700    1.031485  0.224737  0.211255        0           1       0   
4    0.852700    1.031485  0.224737  0.211255        0           1       0   
5    0.852700    1.031485  0.224737  0.211255        0           1       0   
6    0.852700    1.031485  0.233122  0.219138        0           1       0   
7    0.656135    1.033039  0.250139  0.212415        0           1       0   
8    0.671064    1.011142  0.222369  0.198447        0           1       0   
9    0.671064    1.011142  0.228243  0.203689        0           1       0   

   Month Value  
0            8  
1            8  
2            8  
3            8  
4            8  
5            8  
6            8  
7            8  
8            8  
9            8  

[10 rows x 21 columns]

**Another Checkpoint**

In [33]:
df_preprocessed = df_mod.copy()
df_preprocessed.head()

发货期          型号   矿机价格   单T价格      购机当日币价￥   累计挖矿BTC     累计挖矿RMB  \
0 2019-08-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
1 2019-08-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
2 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
3 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
4 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   

   每T理论产出（难度）    历史7日币价平均    历史10日币价平均  ...    历史30日币价平均    历史60日币价平均  \
0    0.000025  79528.0017  80511.71118  ...  73343.31956  74605.94049   
1    0.000025  79528.0017  80511.71118  ...  73343.31956  74605.94049   
2    0.000025  79528.0017  80511.71118  ...  73343.31956  74605.94049   
3    0.000025  79528.0017  80511.71118  ...  73343.31956  74605.94049   
4    0.000025  79528.0017  80511.71118  ...  73343.31956  74605.94049   

   历史30日币价波动率  历史60日币价波动率   ROI BTC     ROI ￥  M20S-68  S17 PRO-50  S9K-14  \
0      0.8527    1.031485  0.235761  0.221619        0           1       0   
1      0.8527    1.031485  0.235761  0.221619        0           1       0   
2      0.8527    1.031485  0.224737  0.211255        0           1       0   
3      0.8527    1.031485  0.224737  0.211255        0           1       0   
4      0.8527    1.031485  0.224737  0.211255        0           1       0   

   Month Value  
0            8  
1            8  
2            8  
3            8  
4            8  

[5 rows x 21 columns]

## Create the targets

In [34]:
#find the median of 'ROI BTC'
df_preprocessed['ROI ￥'].median()

0.254817705

In [35]:
targets = np.where(df_preprocessed['ROI ￥']>
                  df_preprocessed['ROI ￥'].median(),1,0)

In [36]:
targets

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [37]:
df_preprocessed['Higher return'] = targets

In [38]:
df_preprocessed.head()

发货期          型号   矿机价格   单T价格      购机当日币价￥   累计挖矿BTC     累计挖矿RMB  \
0 2019-08-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
1 2019-08-15  S17 PRO-50  26500  530.0  70593.67089  0.088502  5872.89197   
2 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
3 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   
4 2019-08-15  S17 PRO-50  27800  556.0  70593.67089  0.088502  5872.89197   

   每T理论产出（难度）    历史7日币价平均    历史10日币价平均  ...    历史60日币价平均  历史30日币价波动率  \
0    0.000025  79528.0017  80511.71118  ...  74605.94049      0.8527   
1    0.000025  79528.0017  80511.71118  ...  74605.94049      0.8527   
2    0.000025  79528.0017  80511.71118  ...  74605.94049      0.8527   
3    0.000025  79528.0017  80511.71118  ...  74605.94049      0.8527   
4    0.000025  79528.0017  80511.71118  ...  74605.94049      0.8527   

   历史60日币价波动率   ROI BTC     ROI ￥  M20S-68  S17 PRO-50  S9K-14  Month Value  \
0    1.031485  0.235761  0.221619        0           1       0            8   
1    1.031485  0.235761  0.221619        0           1       0            8   
2    1.031485  0.224737  0.211255        0           1       0            8   
3    1.031485  0.224737  0.211255        0           1       0            8   
4    1.031485  0.224737  0.211255        0           1       0            8   

   Higher return  
0              0  
1              0  
2              0  
3              0  
4              0  

[5 rows x 22 columns]

In [39]:
#这一行代码是后加的，为了避免下文出现bug
df_preprocessed = df_preprocessed.drop(['型号','发货期','ROI ￥','ROI BTC','累计挖矿BTC', '累计挖矿RMB','单T价格','Month Value', '历史7日币价平均'],axis=1)

In [40]:
targets.sum()/targets.shape[0]

0.48936170212765956

In [41]:
#data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            #'Daily Work Load Average','Distance to Work'],axis=1)

## Select the inputs for the regression

In [42]:
df_preprocessed.shape

(47, 13)

In [43]:
unscaled_inputs = df_preprocessed.iloc[:,:-1]

## Standardize the data

In [44]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
Higher_return_scaler = StandardScaler()

In [45]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [46]:
unscaled_inputs.columns.values

array(['矿机价格', '购机当日币价￥', '每T理论产出（难度）', '历史10日币价平均', '历史14日币价平均',
       '历史30日币价平均', '历史60日币价平均', '历史30日币价波动率', '历史60日币价波动率', 'M20S-68',
       'S17 PRO-50', 'S9K-14'], dtype=object)

In [47]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['M20S-68','S17 PRO-50','S9K-14']

In [48]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [49]:
higher_scaler = CustomScaler(columns_to_scale)

In [50]:
higher_scaler.fit(unscaled_inputs)

C:\Users\ding_\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['矿机价格', '购机当日币价￥', '每T理论产出（难度）', '历史10日币价平均', '历史14日币价平均', '历史30日币价平均', '历史60日币价平均', '历史30日币价波动率', '历史60日币价波动率'],
       copy=None, with_mean=None, with_std=None)

In [51]:
scaled_inputs = higher_scaler.transform(unscaled_inputs)

C:\Users\ding_\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


In [52]:
scaled_inputs

矿机价格   购机当日币价￥  每T理论产出（难度）  历史10日币价平均  历史14日币价平均  历史30日币价平均  \
0   1.013320  0.263809   -0.147442   1.393628   1.238884   0.542032   
1   1.013320  0.263809   -0.147442   1.393628   1.238884   0.542032   
2   1.154662  0.263809   -0.147442   1.393628   1.238884   0.542032   
3   1.154662  0.263809   -0.147442   1.393628   1.238884   0.542032   
4   1.154662  0.263809   -0.147442   1.393628   1.238884   0.542032   
5   1.154662  0.263809   -0.147442   1.393628   1.238884   0.542032   
6   1.045937  0.263809   -0.147442   1.393628   1.238884   0.542032   
7   1.013320  0.766083   -0.147442   0.668594   1.107491   0.639761   
8   1.089427  0.383235   -0.147442   0.323514   0.580808   0.750816   
9   1.013320  0.383235   -0.147442   0.323514   0.580808   0.750816   
10  0.980702  0.658283   -0.147442   0.131607   0.253882   0.792061   
11  0.719761  0.658283   -0.147442   0.131607   0.253882   0.792061   
12  0.904594  0.501762   -0.147442   0.392054   0.306580   0.574649   
13  0.850232  0.442130   -0.147442   0.256117   0.399830   0.427036   
14 -0.041316 -0.054580   -0.147442  -1.560747  -1.734362  -2.058943   
15 -0.041316 -0.176332   -0.147442  -0.883320  -1.293543  -1.880528   
16  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
17  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
18  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
19  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
20  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
21  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
22  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
23  0.252243 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
24  0.306605 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
25  0.828487  0.396278   -0.147442   0.318442   0.478623   0.778299   
26  0.480566  0.668145   -0.147442   0.109818   0.213053   0.823960   
27  0.415331 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
28  0.143517 -0.481973   -0.147442  -1.759990  -1.803125  -1.024422   
29  0.034792 -1.118009   -0.147442  -2.161207  -2.083281  -2.259993   
30  0.013047 -1.118009   -0.147442  -2.161207  -2.083281  -2.259993   
31 -0.057624 -0.054580   -0.147442  -1.560747  -1.734362  -2.058943   
32 -0.041316 -1.118009   -0.147442  -2.161207  -2.083281  -2.259993   
33 -0.057624 -0.176332   -0.147442  -0.883320  -1.293543  -1.880528   
34 -0.052188 -0.176332   -0.147442  -0.883320  -1.293543  -1.880528   
35 -1.503670  0.760844   -0.147442  -0.228095  -0.211618   0.469606   
36 -1.514543  1.257665   -0.147442   0.000422  -0.077897   0.507984   
37 -1.514543  1.062965   -0.147442   0.230889   0.063924   0.519255   
38 -1.514543  1.350618   -0.147442   0.509239   0.252957   0.518490   
39 -1.514543  1.336274   -0.147442   0.786181   0.432013   0.503980   
40 -1.514543  1.285365   -0.147442   1.045155   0.607075   0.504594   
41 -1.585214  0.263809   -0.147442   1.393628   1.238884   0.542032   
42 -1.617832  0.396278   -0.147442   0.318442   0.478623   0.778299   
43 -1.652624  0.397348   -0.147442   0.267378   0.430402   0.446604   
44 -1.655886  0.323519   -0.147442   0.206850   0.302571   0.410239   
45 -1.677631 -0.661867   -0.147442  -0.847079  -0.495637   0.019880   
46 -1.706987 -5.284669    6.782330  -1.759990  -1.803125  -1.024422   

    历史60日币价平均  历史30日币价波动率  历史60日币价波动率  M20S-68  S17 PRO-50  S9K-14  
0    0.748253    1.103092    1.232567        0           1       0  
1    0.748253    1.103092    1.232567        0           1       0  
2    0.748253    1.103092    1.232567        0           1       0  
3    0.748253    1.103092    1.232567        0           1       0  
4    0.748253    1.103092    1.232567        0           1       0  
5    0.748253    1.103092    1.232567        0           1       0  
6    0.748253    1.103092    1.232567        0           1       0  
7    0.975962   -0.071669    1.240080        0 

In [53]:
scaled_inputs.shape

(47, 12)

In [54]:
scaled_inputs.shape

(47, 12)

## Split the data into train&test and shuffle

**Import the relevant module**

In [55]:
from sklearn.model_selection import train_test_split

**Split**

In [56]:
train_test_split(scaled_inputs,targets)

[        矿机价格   购机当日币价￥  每T理论产出（难度）  历史10日币价平均  历史14日币价平均  历史30日币价平均  \
 20  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
 6   1.045937  0.263809   -0.147442   1.393628   1.238884   0.542032   
 42 -1.617832  0.396278   -0.147442   0.318442   0.478623   0.778299   
 35 -1.503670  0.760844   -0.147442  -0.228095  -0.211618   0.469606   
 32 -0.041316 -1.118009   -0.147442  -2.161207  -2.083281  -2.259993   
 21  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
 30  0.013047 -1.118009   -0.147442  -2.161207  -2.083281  -2.259993   
 16  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
 0   1.013320  0.263809   -0.147442   1.393628   1.238884   0.542032   
 3   1.154662  0.263809   -0.147442   1.393628   1.238884   0.542032   
 18  0.360968 -0.471809   -0.147442  -0.031862   0.133701   0.324365   
 37 -1.514543  1.062965   -0.147442   0.230889   0.063924   0.519255   
 13  0.850232  0.442130   -0.147442   0.256117   0.399830   0.42

In [57]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size = 0.8,test_size = 0.2,random_state=20)

In [58]:
print (x_train.shape,y_train.shape)

(37, 12) (37,)


In [59]:
print (x_test.shape,y_test.shape)

(10, 12) (10,)


## Logistic regression with sklearn

In [60]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

## Training the model

In [61]:
reg = LogisticRegression()

In [62]:
reg.fit(x_train,y_train)

C:\Users\ding_\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [63]:
reg.score(x_train,y_train)

0.918918918918919

**Manually check the accuracy**

In [64]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [65]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [66]:
model_outputs == y_train

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [67]:
np.sum((model_outputs==y_train))

34

In [68]:
model_outputs.shape[0]

37

In [69]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.918918918918919

## Finding the intercept and coefficients

In [70]:
reg.intercept_

array([0.02907576])

In [71]:
reg.coef_

array([[-1.31397525,  0.48747837,  0.23385014, -0.62333187, -0.60975621,
        -0.07017273, -0.0604862 , -0.02062755,  0.73675809,  0.58070174,
        -1.10600674,  0.55438076]])

In [72]:
unscaled_inputs.columns.values

array(['矿机价格', '购机当日币价￥', '每T理论产出（难度）', '历史10日币价平均', '历史14日币价平均',
       '历史30日币价平均', '历史60日币价平均', '历史30日币价波动率', '历史60日币价波动率', 'M20S-68',
       'S17 PRO-50', 'S9K-14'], dtype=object)

In [73]:
feature_name = unscaled_inputs.columns.values

In [74]:
summary_table = pd.DataFrame(columns = ['Feature name'],data = feature_name )

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table


Feature name  Coefficient
0          矿机价格    -1.313975
1       购机当日币价￥     0.487478
2    每T理论产出（难度）     0.233850
3     历史10日币价平均    -0.623332
4     历史14日币价平均    -0.609756
5     历史30日币价平均    -0.070173
6     历史60日币价平均    -0.060486
7    历史30日币价波动率    -0.020628
8    历史60日币价波动率     0.736758
9       M20S-68     0.580702
10   S17 PRO-50    -1.106007
11       S9K-14     0.554381

In [75]:
summary_table.index = summary_table.index+1

summary_table.loc[0] = ['Intercept',reg.intercept_[0]]

suammary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
1          矿机价格    -1.313975
2       购机当日币价￥     0.487478
3    每T理论产出（难度）     0.233850
4     历史10日币价平均    -0.623332
5     历史14日币价平均    -0.609756
6     历史30日币价平均    -0.070173
7     历史60日币价平均    -0.060486
8    历史30日币价波动率    -0.020628
9    历史60日币价波动率     0.736758
10      M20S-68     0.580702
11   S17 PRO-50    -1.106007
12       S9K-14     0.554381
0     Intercept     0.029076

## Interpreting the coefficients

In [76]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
1          矿机价格    -1.313975    0.268750
2       购机当日币价￥     0.487478    1.628205
3    每T理论产出（难度）     0.233850    1.263455
4     历史10日币价平均    -0.623332    0.536155
5     历史14日币价平均    -0.609756    0.543483
6     历史30日币价平均    -0.070173    0.932233
7     历史60日币价平均    -0.060486    0.941307
8    历史30日币价波动率    -0.020628    0.979584
9    历史60日币价波动率     0.736758    2.089152
10      M20S-68     0.580702    1.787292
11   S17 PRO-50    -1.106007    0.330878
12       S9K-14     0.554381    1.740863
0     Intercept     0.029076    1.029503

In [77]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
9    历史60日币价波动率     0.736758    2.089152
10      M20S-68     0.580702    1.787292
12       S9K-14     0.554381    1.740863
2       购机当日币价￥     0.487478    1.628205
3    每T理论产出（难度）     0.233850    1.263455
0     Intercept     0.029076    1.029503
8    历史30日币价波动率    -0.020628    0.979584
7     历史60日币价平均    -0.060486    0.941307
6     历史30日币价平均    -0.070173    0.932233
5     历史14日币价平均    -0.609756    0.543483
4     历史10日币价平均    -0.623332    0.536155
11   S17 PRO-50    -1.106007    0.330878
1          矿机价格    -1.313975    0.268750

## Testing the model

In [78]:
reg.score(x_test,y_test)

0.9

In [79]:
predicted_proba = reg.predict_proba(x_test)

predicted_proba

array([[0.96517795, 0.03482205],
       [0.89897537, 0.10102463],
       [0.02576104, 0.97423896],
       [0.1548057 , 0.8451943 ],
       [0.95836712, 0.04163288],
       [0.32462622, 0.67537378],
       [0.1659819 , 0.8340181 ],
       [0.93219149, 0.06780851],
       [0.03998308, 0.96001692],
       [0.13403873, 0.86596127]])

In [80]:
predicted_proba.shape

(10, 2)

In [81]:
predicted_proba[:,1]

array([0.03482205, 0.10102463, 0.97423896, 0.8451943 , 0.04163288,
       0.67537378, 0.8340181 , 0.06780851, 0.96001692, 0.86596127])

## Save the model

In [82]:
#import pickle

In [83]:
#with open('model','wb') as file:
   # pickle.dump(reg,file)

In [84]:
#with open('scaler','wb')as file:
   # pickle.dump(higher_scaler,file)